# Generated by Django 2.2.19 on 2022-08-08 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220808_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='recipes',
        ),
        migrations.AddField(
            model_name='carts',
            name='recipes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='recipes.Recipes', verbose_name='Рецепты'),
            preserve_default=False,
        ),
    ]
