# Generated by Django 2.2.19 on 2022-08-11 21:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_auto_20220811_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'recipe')},
        ),
    ]
