# Generated by Django 2.2.19 on 2022-08-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'guest'), ('auth_user', 'auth_user'), ('admin', 'admin')], default='guest', help_text='Введите роль пользователя', max_length=16, verbose_name='Роль пользователя'),
        ),
    ]
